components_manager:
  coro_pool:
    initial_size: 500
    max_size: 1000
  task_processors:
    main-task-processor:
      worker_threads: 4
    fs-task-processor:
      worker_threads: 2
  default_task_processor: main-task-processor

  components:
    server:
      listener:
        port: 3000
        task_processor: main-task-processor
    logging:
      fs-task-processor: fs-task-processor
      loggers:
        default:
          file_path: '@stderr'
          level: info
          overflow_behavior: discard
    
    postgres-db-1:
      dbconnection: 'postgresql://mathforces:mathforces_pass@127.0.0.1:5432/mathforces_db'
      blocking_task_processor: fs-task-processor
      dns_resolver: async
    
    dns-client:
      fs-task-processor: fs-task-processor

    http-client:
      fs-task-processor: fs-task-processor
      pool-statistics-disable: true

    handler-ping:
      path: /ping
      method: GET
      task_processor: main-task-processor

    handler-login:
      path: /api/login/email
      method: POST
      task_processor: main-task-processor

    handler-contests:
      path: /api/contests
      method: GET, POST
      task_processor: main-task-processor

    handler-ratings:
      path: /api/ratings
      method: GET
      task_processor: main-task-processor

    handler-archive:
      path: /api/archive/tasks
      method: GET
      task_processor: main-task-processor

    handler-registercode:
      path: /api/register/request_code
      method: POST
      task_processor: main-task-processor

    handler-registeremail:
      path: /api/register/email
      method: POST
      task_processor: main-task-processor

    handler-users:
      path: /api/users
      method: GET
      task_processor: main-task-processor

    handler-userssearch:
      path: /api/users/search
      method: GET
      task_processor: main-task-processor

    handler-usersprofile:
      path: /api/users/profile
      method: GET, POST
      task_processor: main-task-processor

    handler-usersrole:
      path: /api/users/role
      method: POST
      task_processor: main-task-processor

    handler-usersban:
      path: /api/users/ban
      method: POST
      task_processor: main-task-processor

    handler-usersblogaccess:
      path: /api/users/blog_access
      method: POST
      task_processor: main-task-processor

    handler-friendslist:
      path: /api/friends/list
      method: GET
      task_processor: main-task-processor

    handler-friendsadd:
      path: /api/friends/add
      method: POST
      task_processor: main-task-processor

    handler-friendsremove:
      path: /api/friends/remove
      method: POST
      task_processor: main-task-processor

    handler-blogposts:
      path: /api/blog/posts
      method: GET, POST
      task_processor: main-task-processor

    handler-blogcomments:
      path: /api/blog/comments
      method: GET, POST
      task_processor: main-task-processor

    handler-compiletypst:
      path: /api/compile_typst
      method: POST
      task_processor: main-task-processor

    handler-adminmycontests:
      path: /api/admin/my_contests
      method: GET
      task_processor: main-task-processor

    handler-admincontest:
      path: /api/admin/contest
      method: POST
      task_processor: main-task-processor

    handler-admintask:
      path: /api/admin/task
      method: POST
      task_processor: main-task-processor

    handler-results:
      path: /api/results
      method: GET
      task_processor: main-task-processor

    handler-adminratecontest:
      path: /api/admin/rate_contest
      method: POST
      task_processor: main-task-processor

    handler-contestsvirtual:
      path: /api/contests/virtual
      method: POST
      task_processor: main-task-processor

    handler-tasks:
      path: /api/tasks
      method: GET
      task_processor: main-task-processor

    handler-submit:
      path: /api/submit
      method: POST
      task_processor: main-task-processor

    handler-submissions:
      path: /api/submissions
      method: GET
      task_processor: main-task-processor

    handler-submissionsall:
      path: /api/submissions/all
      method: GET
      task_processor: main-task-processor

    handler-hacks:
      path: /api/hacks
      method: GET, POST
      task_processor: main-task-processor

    handler-oauthcallback:
      path: /api/oauth_callback_client
      method: GET, POST
      task_processor: main-task-processor
